name: rss
version: 0.3.3
author: Joris Hermans <hermansj@gmail.com>
description: Rss parser for dart.
homepage: https://github.com/jorishermans/dart-rss
dependencies:
  xmlstream: '0.8.8'
  observe: '0.9.1+1'
dev_dependencies:
  unittest: '>=0.9.0 <0.9.1'
