name: rss
version: 0.2.2
author: Joris Hermans <hermansj@gmail.com>
description: Rss parser for dart.
homepage: https://github.com/jorishermans/dart-rss
dependencies:
  xmlstream: '0.8.6'
  unittest: '>=0.9.0 <0.9.1'

